import { AZUL_PRIMARIO } from '../constants';

export const styles = {
  fullScreen: { minHeight: '100vh', width: '100%', display: 'flex', flexDirection: 'column', backgroundColor: '#f3f4f6', fontFamily: 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif' },
  header: { backgroundColor: AZUL_PRIMARIO, color: 'white', padding: '15px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: '0 2px 5px rgba(0,0,0,0.2)', position: 'sticky', top: 0, zIndex: 1000 },
  containerCentral: { width: '100%', maxWidth: '1600px', margin: '0 auto', display: 'flex', flexDirection: 'column', flex: 1, padding: '0 20px' },
  card: { flex: 1, background: 'white', padding: '20px', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', display: 'flex', flexDirection: 'column', marginBottom: '20px' },
  inputGroup: { display: 'flex', flexDirection: 'column', width: '100%' },
  label: { fontSize: '11px', fontWeight: 'bold', marginBottom: '5px', color: '#4b5563', textTransform: 'uppercase', letterSpacing: '0.5px' },
  input: { padding: '8px 10px', border: '1px solid #d1d5db', borderRadius: '4px', width: '100%', fontSize: '13px', outline: 'none', height: '38px', boxSizing: 'border-box', backgroundColor: '#fff' },
  select: { padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', width: '100%', fontSize: '14px', outline: 'none', backgroundColor: 'white', cursor: 'pointer' },
  btnAzul: { backgroundColor: AZUL_PRIMARIO, color: 'white', border: 'none', borderRadius: '6px', padding: '12px', fontWeight: 'bold', cursor: 'pointer', width: '100%', fontSize: '14px', transition: 'background 0.2s' },
  btnSair: { backgroundColor: '#dc2626', color: 'white', border: 'none', borderRadius: '4px', padding: '8px 16px', fontWeight: 'bold', cursor: 'pointer', fontSize: '12px' },
  menu: { position: 'fixed', top: 0, height: '100%', backgroundColor: AZUL_PRIMARIO, zIndex: 2000, transition: 'left 0.3s', paddingTop: '80px', paddingLeft: '20px', boxShadow: '4px 0 10px rgba(0,0,0,0.2)', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', width: '260px' },
  menuItem: { display: 'block', background: 'none', border: 'none', color: 'white', padding: '12px 0', fontSize: '0.95rem', cursor: 'pointer', textAlign: 'left', width: '100%', opacity: 0.9 },
  menuSubItem: { display: 'block', background: 'none', border: 'none', color: 'white', padding: '8px 0 8px 15px', fontSize: '0.9rem', cursor: 'pointer', textAlign: 'left', width: '100%', fontWeight: 'bold' },
  toast: { position: 'fixed', bottom: '20px', right: '20px', backgroundColor: '#10b981', color: 'white', padding: '15px 25px', borderRadius: '8px', fontWeight: 'bold', boxShadow: '0 4px 12px rgba(0,0,0,0.3)', zIndex: 9999 },
  badge: { padding: '2px 8px', borderRadius: '10px', fontSize: '10px', backgroundColor: 'rgba(255,255,255,0.2)', marginLeft: '10px', border: '1px solid rgba(255,255,255,0.4)', textTransform: 'uppercase' },
  dragHandle: { cursor: 'grab', display: 'flex', alignItems: 'center', padding: '0 10px', color: '#9ca3af', fontSize: '20px' },
  sinoContainer: { position: 'relative', cursor: 'pointer', marginRight: '20px' },
  sinoBadge: { position: 'absolute', top: '-5px', right: '-5px', backgroundColor: '#ef4444', color: 'white', borderRadius: '50%', width: '18px', height: '18px', fontSize: '11px', display: 'flex', justifyContent: 'center', alignItems: 'center', fontWeight: 'bold' },
  dropdownNotificacao: { position: 'absolute', top: '40px', right: '0', backgroundColor: 'white', width: '320px', boxShadow: '0 5px 15px rgba(0,0,0,0.2)', borderRadius: '8px', zIndex: 3000, overflow: 'hidden' },
  gridPrincipal: { display: 'flex', gap: '25px', height: 'calc(100vh - 140px)', alignItems: 'flex-start' },
  painelEsquerdo: { width: '350px', backgroundColor: 'white', padding: '25px', borderRadius: '12px', boxShadow: '0 4px 15px rgba(0,0,0,0.1)', display: 'flex', flexDirection: 'column', gap: '15px' },
  painelDireito: { flex: 1, display: 'flex', flexDirection: 'column', height: '100%' },
  gridCards: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', overflowY: 'auto', paddingRight: '10px', paddingBottom: '20px', alignContent: 'start' },
  cardVeiculo: { borderRadius: '12px', padding: '15px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', display: 'flex', flexDirection: 'column', gap: '10px', borderLeftWidth: '8px', borderLeftStyle: 'solid', transition: 'all 0.2s', backgroundColor: 'white' },
  iconeAcao: { fontSize: '22px', cursor: 'pointer', border: 'none', background: 'transparent' },
  iconeLixeira: { fontSize: '24px', cursor: 'pointer', color: 'red', border: 'none', background: 'transparent' },
  textoStatusTempo: { fontSize: '13px', fontWeight: 'bold', color: '#4b5563', display: 'flex', alignItems: 'center', gap: '5px' },
  selectOperacao: {padding: '4px 8px', boderRadius: '6px', border: '1px solid #bfdbfe', backgroundColor: '#eff6ff', color: '#1e3a8a', fontWeight: 'bold', fontSize: '11px', cursor: 'pointer', outline: 'none', width: '100%', appearance: 'none', textAlign: 'center'},
  btnAdd: { backgroundColor: '#10b981', color: 'white', border: 'none', borderRadius: '6px', padding: '10px', fontWeight: 'bold', cursor: 'pointer', width: '100%' }
};